spring:
    datasource:
        url: jdbc:h2:mem:tacocloud
        username: sa
        password:
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true

    h2:
        console:
            enabled: true
    security:
        oauth2:
            client:
                registration:
                    github:
                        clientId: ${CLIENT_ID}
                        clientSecret: ${CLIENT_SECRET}
                        scope: read:user,user:email