spring:
    datasource:
        url: jdbc:h2:mem:tacocloud
        username: sa
        password:
        driverClassName: org.h2.Driver
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        defer-datasource-initialization: true

    h2:
        console:
            enabled: true
    security:
        oauth2:
            client:
                registration:
                    github:
                        clientId: Ov23liVFjaJfNXK1EeNI
                        clientSecret: f16ac671836c30ffc3e293907bbcda59a9990208
                        scope: read:user,user:email